### ISSUE TITLE
SSE too conservative

### ISSUE THREAD

**Issue by eile** [BlueBrain/Livre#113]
To reproduce: ```vglrun ../release/bin/livre --volume fivox:// --frames '2 4' --sse 1```
Then full-screen window.

Resolution is about 1k, which means that the total volume size should be around 1GB (cubic volume, ~1k px high in the front-most bricks, less in the "deeper" bricks)

It is more than 8 GB (see attached screenshot w/ stats): ![livre2](https://cloud.githubusercontent.com/assets/354947/9274772/ad26e00c-4298-11e5-9f55-fb43d95ca7a0.png)

**Comment by bilgili** [comment]
I am trying to understand this issue. According to the picture the full detailed volume has 8x8x8 blocks. For the 1k resolution the best lod is 4x4x4 ( 4 by 336 is ~ 1024 ). Each block is approximately 28MB and 64 blocks is app  2GB ( so volume most probably be between 1 to 2 GB ). One of the thing is, I never un-cache the level 0 and   if you have switched between frames, these are never unloaded. Here there is 2 frames and if you have switched between frames and level 0 is loaded the 3 gb almost is un-cachable. With the rendered blocks it seems it is possible to exceed the supposed limit. I will disable level 0 caching.

**Comment by eile** [comment]
Not sure what the conclusion is - if there is one. I agree with the conclusion that the data size per frame should be 1-2 GB. I do not remember if I used more then one time step, but should be easy to reproduce.

**Comment by eile** [comment]
Definitely a single frame. Just got >3GB for a 960x600 window.

**Comment by eile** [comment]
Just redid this experiment with different parameters:
```env EQ_WINDOW_IATTR_HINT_HEIGHT=256 EQ_WINDOW_IATTR_HINT_WIDTH=256 ../release/bin/livre.app/Contents/MacOS/livre --sse 1 --volume 'mem://#4096,4096,4096,256'```

Yields:
```
Data cache CPU
  Used Memory: 576/768MB
  Block Count: 36
  Cache hits: 0 (0%)
  Cache misses: 36
  100% loaded
Texture cache GPU
  Used Memory: 576/384MB
  Block Count: 36
  Cache hits: 0 (0%)
  Cache misses: 36
Total resolution [       4096       4096       4096 ] depth 5
Block resolution [        256        256        256 ]
mm/voxel [    0.24414    0.24414    0.24414 ]
```

-> 36 blocks of 256^3 get rendered for a 256^2 window in the default camera position. This is at least one LOD too much, since the front of the volume exactly fills the window (and the back less due to perspective frustum). Ideally only one block would be loaded, but I would accept eight.

**Comment by eile** [comment]
Also document if bricks have at most or at least the given SSE
