### ISSUE TITLE
Livre - RESTBridge - cppnetlib compilation error

### ISSUE THREAD

**Issue by egparedes** [BlueBrain/Livre#131]
Livre compilation breaks in my workstation due to an unresolved dependency problem in the RESTBridge subproject. Apparently the 'cppnetlib' dependency is not being detected nor cloned. I have tried using CMake 2.8.12.2 and CMake 3.3.1 and it breaks in both cases, although in a different way.

Using CMake 2.8.12.2, the CMake configuration step finishes without problems but then the compilation fails because the compiler doesn't find the cppnetlib headers. Findcppnetlib cmake module it is not able to find the headers (since the cppnetlib repository was not checked out but oddly the CMake configuration process goes on):

-----------------------------
 cmake version 2.8.12.2
-----------------------------
```
//->  CPPNETLIB_PATH =
//->  CPPNETLIB_INCLUDE_DIR = CPPNETLIB_INCLUDE_DIR-NOTFOUND
//->  CPPNETLIB_INCLUDE_DIRS =
//->  CPPNETLIB_LIBRARIES =
//->  CPPNETLIB_FOUND =
-- Configured RESTBridge [4f16cfb] with Boost cppnetlib FlatBuffers zeq
-- Configured Tuvok [aa30403] with BISON FLEX OpenGL OpenMP Qt5Core
Qt5OpenGL ZLIB
-- Configured Livre [f2a4571] with Boost Collage dash Equalizer
FlatBuffers GLEW_MX LibJpegTurbo Lunchbox OpenGL OpenMP PNG Qt5Core
Qt5OpenGL Qt5Widgets RESTBridge Threads Tuvok zeq WITHOUT BBPTestData
VTune ISC
-- Configuring done
-- Generating done
-- Build files have been written to:
/home/egparedes/Development/github/upstream/Livre/build
```

-----------------------------

Using CMake 3.3.1, the cppnetlib repository is not checked out but the CMake step stops and shows
an error since the library headers and binaries cannot be found. When running this CMake version a second time in the same folder, the repository is finally checked out but CMakes is still not able to find the library:

-----------------------------
 cmake version 3.3.1 - 1st run
-----------------------------

```
//->  CPPNETLIB_PATH =
//->  CPPNETLIB_INCLUDE_DIR = CPPNETLIB_INCLUDE_DIR-NOTFOUND
//->  CPPNETLIB_INCLUDE_DIRS =
//->  CPPNETLIB_LIBRARIES =
//->  CPPNETLIB_FOUND =
CMake Error at
/opt/cmake-3.3.1/share/cmake-3.3/Modules/FindPkgConfig.cmake:340 (message):
  A required package was not found
Call Stack (most recent call first):
  /opt/cmake-3.3.1/share/cmake-3.3/Modules/FindPkgConfig.cmake:502
(_pkg_check_modules_internal)
  CMake/common/CommonPackage.cmake:97 (pkg_check_modules)
  RESTBridge/CMakeLists.txt:31 (common_package)
```

-----------------------------
 cmake version 3.3.1 - 2nd run
-----------------------------

```
//->  CPPNETLIB_PATH =
//->  CPPNETLIB_INCLUDE_DIR = CPPNETLIB_INCLUDE_DIR-NOTFOUND
//->  CPPNETLIB_INCLUDE_DIRS =
//->  CPPNETLIB_LIBRARIES =
//->  CPPNETLIB_FOUND =
-- git clone --recursive https://github.com/cpp-netlib/cpp-netlib.git
/home/egparedes/Development/github/upstream/Livre/cppnetlib [d3e884f]
Submodule 'deps/asio' (git://github.com/cpp-netlib/asio) registered for
path 'deps/asio'
Submodule 'deps/gmock' (git://github.com/cpp-netlib/gmock) registered
for path 'deps/gmock'
Submodule 'deps/gtest' (git://github.com/cpp-netlib/gtest) registered
for path 'deps/gtest'
Submodule 'deps/igloo' (git://github.com/joakimkarlsson/igloo.git)
registered for path 'deps/igloo'
Submodule 'uri' (git://github.com/cpp-netlib/uri) registered for path 'uri'
Submodule path 'deps/asio': checked out
'e80030ffa178dbcca11d84ab607a87495a711a17'
Submodule path 'deps/gmock': checked out
'6b1759c3816d574bddde3e1725c51a811c8870e7'
Submodule path 'deps/gtest': checked out
'a6772271f71672e889776bfe49ec4efd9da036df'
Submodule path 'deps/igloo': checked out
'7d5ad81e705e61453adc16990dab8c825b41e20b'
Submodule path 'uri': checked out
'9567e16a5936bf0ebcea8b33d56863251dc94e9b'
-- Found ICU header files in /usr/include/x86_64-linux-gnu
-- Found ICU libraries: /usr/lib/x86_64-linux-gnu/libicuuc.so
-- Boost version: 1.54.0
-- Found the following Boost libraries:
--   system
--   regex
--   filesystem
-- Found OpenSSL:
/usr/lib/x86_64-linux-gnu/libssl.so;/usr/lib/x86_64-linux-gnu/libcrypto.so
(found version "1.0.1f")
-- Found Threads: TRUE
-- Performing Test HAVE_STD11
-- Performing Test HAVE_STD11 - Success
-- C++ Compiler ID: GNU
-- C++ Flags:  -std=c++11 -std=c++11 link flags:
-- CPP-NETLIB options selected:
--   CPP-NETLIB_BUILD_SHARED_LIBS:      ON    (Build cpp-netlib as
shared libraries: OFF, ON)
--   CPP-NETLIB_BUILD_SINGLE_LIB:       OFF    (Build cpp-netlib into a
single library: OFF, ON)
--   CPP-NETLIB_BUILD_TESTS:            ON    (Build the unit tests: ON,
OFF)
--   CPP-NETLIB_BUILD_EXAMPLES:         OFF    (Build the examples using
cpp-netlib: ON, OFF)
--   CPP-NETLIB_ALWAYS_LOGGING:         OFF    (Allow cpp-netlib to log
debug messages even in non-debug mode: ON, OFF)
--   CPP-NETLIB_DISABLE_LOGGING:        OFF    (Disable logging
definitely, no logging code will be generated or compiled: ON, OFF)
--   CPP-NETLIB_DISABLE_LIBCXX:         OFF    (Disable using libc++
when building with clang: ON, OFF)
--   CPP-NETLIB_DISABLE_FEATURE_TESTS:  OFF    (Disable the feature
tests (which may use a network connection): ON, OFF)
-- CMake build options selected:
-- Found PythonInterp: /usr/bin/python (found suitable version "2.7.6",
minimum required is "2")
-- Found Doxygen: /usr/bin/doxygen (found version "1.8.6")
-- Boost version: 1.54.0
-- Found the following Boost libraries:
--   system
--   filesystem
C++ Flags:  -std=c++11 -std=c++11 -std=c++11 link flags:
-- Found GTest: gtest
CMake Error at
/opt/cmake-3.3.1/share/cmake-3.3/Modules/FindPackageHandleStandardArgs.cmake:148
(message):
  Could NOT find cppnetlib (missing: CPPNETLIB_LIBRARIES
  CPPNETLIB_INCLUDE_DIR)
Call Stack (most recent call first):
/opt/cmake-3.3.1/share/cmake-3.3/Modules/FindPackageHandleStandardArgs.cmake:388
(_FPHSA_FAILURE_MESSAGE)
  CMake/common/Findcppnetlib.cmake:88 (find_package_handle_standard_args)
  CMake/common/SubProject.cmake:158 (find_package)
  CMake/common/SubProject.cmake:194 (add_subproject)
  RESTBridge/.gitsubprojects:4 (git_subproject)
  CMake/common/SubProject.cmake:211 (include)
  CMake/common/Common.cmake:120 (include)
  RESTBridge/CMakeLists.txt:27 (include)
  ```

**Comment by bilgili** [comment]
What is you linux version ?

**Comment by egparedes** [comment]
Ubuntu LTS 14.04 - Linux 3.16.0-46-generic #62~14.04.1-Ubuntu SMP x86_64 GNU/Linux

**Comment by bilgili** [comment]
Hi,

I just had compiled with :

Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.2 LTS
Release:	14.04
Codename:	trusty

cmake version 3.1.3.

Do you have the cppnetlib and other packages installed ?

**Comment by egparedes** [comment]
Hi Ahmet,

I have just tried to compile newest Livre again and it seems to fail 
exactly the same. I have previously compile Livre on this machine and I 
think I have all the required packages installed, but if there are new 
dependencies, they could be missing.

Anyway, the problem is always related to the cppnetlib subproject, and I 
don't think I can install it from the Ubuntu repositories. I will try to 
do some more tests to see what could be the problem, but right now I 
don't see why it's not compiling here.

Cheers,

      Enrique

On 03.09.2015 11:59, Ahmet Bilgili wrote:
>
> Hi,
>
> I just had compiled with :
>
> Distributor ID: Ubuntu
> Description: Ubuntu 14.04.2 LTS
> Release: 14.04
> Codename: trusty
>
> cmake version 3.1.3.
>
> Do you have the cppnetlib and other packages installed ?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/BlueBrain/Livre/issues/131#issuecomment-137396597>.
>

-- 
Enrique G. Paredes (egparedes@ifi.uzh.ch)
Visualization and MultiMedia Lab - http://vmml.ifi.uzh.ch/
University of Zurich. Department of Informatics

**Comment by egparedes** [comment]
I think the compilation problem with Livre and RESTBridge is as simple as that the cppnetlib CMake find module is not able to locate the cppnetlib installation folder. 

The file “Findcppnetlib.cmake” (line 52) uses this piece of code to detect the cppnetlib installation:

```
find_path(CPPNETLIB_INCLUDE_DIR boost/network.hpp
  HINTS ${CPPNETLIB_ROOT}/include $ENV{CPPNETLIB_ROOT}/include
  ${COMMON_SOURCE_DIR}/cppnetlib ${CMAKE_SOURCE_DIR}/cppnetlib
  /usr/local/include
  /usr/include)
```
but the file "boost/network.hpp” does not exist at all in the cppnetlib folder. Actually, the whole hierarchy "boost/network/…" does not exist in the checked out cppnetlib repository. I’ve never used the cppnetlib but it seems that just checking out the repository is not enough, since the include files do not follow this folder hierarchy. I would really like to know how could you ignore this problem when you compiled Livre in the Linux workstation. Could you tell me which installation folder was detected in your machine for the “cppnetlib”?

**Comment by bilgili** [comment]
Have you done ?

sudo apt-get install libcppnetlib-dev

this should be installing the cppnetlib under boost/network library.

On our cluster, we are using the CPPNETLIB_ROOT env variable. Under include directory there is boost/network.

**Comment by egparedes** [comment]
Yeah, that fixed the problem, you were right. I used the quick filter of Synaptic instead of the apt command line to look for the cppnetlib packages with a wrong name and it couldn't find them. 

Now it works so you can close the issue, thank you.  Anyway, it's quite confusing that cppnetlib appears as a subproject in the project (and the repo is cloned by CMake) when it is not possible to use it in that way.

**Comment by bilgili** [comment]
Yes, you are right, it should have worked. I will open an issue on our side for that.
