### ISSUE TITLE
Draw artifacts when the camera is inside a volume

### ISSUE THREAD

**Issue by chevtche** [BlueBrain/Livre#191]
Draw artifacts when the camera is inside a volume

**Comment by chevtche** [comment]
#192 
#193

**Comment by chevtche** [comment]
#194

**Comment by bilgili** [comment]
@chevtche : Can you add some information beside them ? How many of them done ?

**Comment by chevtche** [comment]
#192 and #193 are done

**Comment by bilgili** [comment]
Also you may want to add story for the the sampling starts at the boundaries of the volume.
