### ISSUE TITLE
Default samples per ray are too low

### ISSUE THREAD

**Issue by tribal-tec** [BlueBrain/Livre#205]
![artefact](https://cloud.githubusercontent.com/assets/701401/11372691/25829268-92cf-11e5-8b7f-63bbb600819a.png)

**Comment by bilgili** [comment]
Unfortunately this information is not enough. I would like to have the command line arguments, data resolution etc.

**Comment by eile** [comment]
```../release/bin/livre.app/Contents/MacOS/livre --max-lod 0``` reproduces a similar image for me. Not exactly hard to figure out from the image. ;)

**Comment by bilgili** [comment]
I am not a genious like you guys, sorry :)

**Comment by tribal-tec** [comment]
yes, the --max-lod 0 was the missing part. sorry.

**Comment by bilgili** [comment]
Fixed with #210
