### ISSUE TITLE
livre exits after ~73 minutes @60 fps

### ISSUE THREAD

**Issue by tribal-tec** [BlueBrain/Livre#212]
When rendering animations for instance. --num-frames by default is now 262143.

**Comment by bilgili** [comment]
NodeId has 18 bits for frame ids. So, more than that needs change in the NodeId.

**Comment by tribal-tec** [comment]
num-frames and frame ID are not so tightly coupled imo. One determines how much frames to render, the other which frames. You could also render the same frame num-frame times.
