### ISSUE TITLE
Some blocks are not rendered with a volume of size (1140,800,1320)

### ISSUE THREAD

**Issue by rdumusc** [BlueBrain/Livre#214]
This is reproducible with both bbic and mem datasources, the volume is cut; only 2 blocks instead 4 seem to be visible at --max-lod=0.

vglrun livre --volume bbic:///gpfs/bbp.cscs.ch/project/proj3/resources/volumes/bbic/allen_average_brain.h5 --max-lod 0
OR
vglrun livre --volume mem:///#1140,800,1320,56 --max-lod 0

![screenshot from 2015-11-30 17 56 58](https://cloud.githubusercontent.com/assets/5166658/11478236/09e9823e-978c-11e5-841b-e1281be43e0f.png)

The code in VolumeDataSourcePlugin.cpp -> fillRegularVolumeInfo() might be a good starting point for debugging, but the conflicting documentation in livre/core/data/NodeId.h between RootNode and NodeId constructors complicate the task.

The reported depth of 4 looks suspicious since the LOD structure is the following:

BBIC file v1 - 0 stacks, 1 volumes
Volume v2 [1140, 800, 1320], block size: 64, #blocks (18, 13, 21)
detailed structure:
Level 0: #blocks (18, 13, 21), size (1140, 800, 1320)
Level 1: #blocks (9, 7, 11), size (570, 400, 660)
Level 2: #blocks (5, 4, 6), size (285, 200, 330)
Level 3: #blocks (3, 2, 3), size (142, 100, 165)
Level 4: #blocks (2, 1, 2), size (71, 50, 82)

However increasing the depth to 5 in fillRegularVolumeInfo() breaks the behaviour in multiple places. This bugs needs further investigations as I couldn't find an easy fix.

**Comment by bilgili** [comment]
I did not understand how "NodeId" and "RootNode" complicate things but we can discuss tomorrow.

**Comment by rdumusc** [comment]
It's no big deal, I only got confused by the implementation yesterday trying to understand what could be the expected values, because RootNode actually has nothing to do with a NodeId, yet it builds one and reuses the fields with different semantics...

**Comment by chevtche** [comment]
"vglrun livre --volume mem:///#1140,800,1320,56 --max-lod 0"
is working as expected... It has 4 blocks

**Comment by rdumusc** [comment]
After some more discussions, it appears that part of the fix is that livreDataSource needs to reimplement internalNodeToLODNode() to filter out invalid block requests

**Comment by rdumusc** [comment]
The fix for the missing blocks is here: https://github.com/BlueBrain/Livre/pull/216
Some adaptiations were also needed in livreDataSources for the BBIC format.
