### ISSUE TITLE
Higher LODs are not loaded while zooming in

### ISSUE THREAD

**Issue by tribal-tec** [BlueBrain/Livre#221]
Launch livre with
```
livre --volume uvf://$HOME/rat.uvf --sse 1 --camera-position "0 0 3"
```

Wait until 100% is loaded (watch statistics), then get closer with camera and keep watching "Loaded" percentage in statistics. It drops down to 0%, so only the fully loaded low-quality detail level is used for rendering.

I can also provide a smaller UVF volume if necessary, just let me know.

**Comment by tribal-tec** [comment]
Even works with the memory data source. Let it load for 100% for initial camera position, then zoom in.

**Comment by bilgili** [comment]
Reporting may have issues. I have to check as well. I have tried it and it uses full details in zoom.
