### ISSUE TITLE
Performance for 1K UVF @ 2K with SSE 1 too low

### ISSUE THREAD

**Issue by tribal-tec** [BlueBrain/Livre#228]
Ask me for UVF, it's a 1K cubed volume of the epileptic slice, but any other sized UVF volume should do as well

```
EQ_WINDOW_IATTR_HINT_HEIGHT=1080 EQ_WINDOW_IATTR_HINT_WIDTH=1920 bin/livre --volume uvf://$HOME/volume.uvf --sse 1 --camera-position "-1 0 0"
```

I get ~2fps on my GTX 480. Reducing the samples-per-ray to 64 gives me 6fps, but it still feels too slow, plus the quality gets bad quickly.

**Comment by bilgili** [comment]
Can you add a screen shot with statistics ? ( Blocksize, transparency everything effects the rendering speed )
Can you define quality gets bad quickly ? 

If number of blocks to be rendered is high, every block is rendered with a pass ( Framebuffer copied to texture and then being rendered onto). Grigory and I are working on a rendererer to have less passes.

**Comment by tribal-tec** [comment]
Well, you know how less numbers for samples-per-ray makes the quality go bad. I'll provide a screenshot with statistics.

**Comment by tribal-tec** [comment]
![1k_cubed_performance](https://cloud.githubusercontent.com/assets/701401/11840313/1c66fb10-a3f5-11e5-9a2d-98f8f7267300.png)

**Comment by bilgili** [comment]
I get it as it is good at the beginning of rendering and gets bad afterwards.

**Comment by eile** [comment]
There is also a bug in the cache stats, I don't think the mem cache should have less data then the GPU cache.

**Comment by bilgili** [comment]
The topic of the issue itself is not a "bug" ( I will double check ) 512 passes ( 512 blocks ) needed for the single frame where the pixel shader is not passing the blocks because of the transparency. 512 texture copies is needed in between.

**Comment by eile** [comment]
True, not a bug.
