### ISSUE TITLE
The cache sizes does not match between memory and GPU

### ISSUE THREAD

**Issue by bilgili** [BlueBrain/Livre#230]
As shown in #228 the cache sizes does not match between cpu and gpu memory.

**Comment by bilgili** [comment]
@tribal-tec , @eile  : Cache size does match between GPU and CPU, because the CPU memory allocation is done using "lunchbox::Buffer" which is greedy on allocation for not reallocating memory, which allocates more than it is needed and this memory is reported. So this is correctly reported.

**Comment by tribal-tec** [comment]
The screenshot showed the opposite where the GPU memory is more greedy than CPU. Confused...

**Comment by bilgili** [comment]
So, I have found the issue. If all the blocks have thse same size, the cache sizes will always match. But if the volumes are like "uvf" ( irregular sizes of blocks ), the GPU cache will result bigger sizes because the texture allocation is done according to the largest size and data is always placed in this texture.
