### ISSUE TITLE
livre --volume fivox:// does not resample bricks when moving camera

### ISSUE THREAD

**Issue by eile** [BlueBrain/Livre#255]

**Comment by bilgili** [comment]
I am not sure this is a bug. It is working as it supposed to be. The default screen space error is 4. It means 4 voxels can be represented as one pixel. The lowest resolutions highest dimension of default fivox volume is 328. If screen is 1080p, then the accepted resolution is 1080/4 = 270 voxels which is around this number. So, it will always find the 0th level of detail as accepted resolution. If you want higher resolutions to be visible you should set the sse to lower numbers. If you set sse to 1 it will find at least to 2nd level of detail. If you want to force a level of detail as minimum use minLod parameter.

**Comment by bilgili** [comment]
Correcting, 1 voxel can be 4 pixels.

**Comment by eile** [comment]
dup #221. Will test again, but I would be surprised if this bug resolved itself.

**Comment by bilgili** [comment]
Regarding to our discussion you have said this was working before and it is not working now. And, I have found that the reason the maths has changed due to Plane was changed into a 4d vector only.  So, I fix that issue so that it is ok. I am not sure it is a dup of #221.

**Comment by eile** [comment]
Not sure what I am missing, but it's not working for me:
```../release/bin/livre.app/Contents/MacOS/livre --volume fivox:// --sse 8```

Wait for the one brick to be sampled and rendered, then zoom in. Note in the screenshot '0% loaded', but no Fivox sampling is happening. No amount of zoom in/out triggers the bricks to be loaded.

Also please remove the noisy debug prong which just appeared, I could not localize it.

In any case update/close the bug when making progress on it. ;)

![screen shot 2016-03-31 at 11 25 50](https://cloud.githubusercontent.com/assets/354947/14171522/bc43b056-f733-11e5-80e6-92b9b2e46b5c.png)

**Comment by bilgili** [comment]
The talk we have made was "When I open fivox with the default state, the resolution is low". And, I am sure I have fixed that. I have asked you personally to try it to close the ticket, my mistake that I did not write it down. So, this is another issue and may be related to #221. 

For the debugging message, may it be you guys doing Fivox ? I don't see such a message in "vglrun ../build/bin/livre"

**Comment by eile** [comment]
Re debug: Possible. @jafyvilla ?

**Comment by eile** [comment]
Re "When I open fivox with the default state, the resolution is low": I don't remember this talk. This ticket was always about "stuck sampling". #113 is "When I open fivox with the default state, the resolution is too high", and as updated today I still think it is.

**Comment by jafyvilla** [comment]
I'm pretty sure that the debug message was not introduced in Fivox, but I tried to find it and couldn't even reproduce it either. Does it show up also using the latest module? other platforms?

**Comment by bilgili** [comment]
Bricks are not re-sampled because  pr #201 broke visible selection while moving the code to SelectVisibles.h, where previous visibles were not cleared. I will add tests for those things when dash is out but setup for a test is not easy currently.
