### ISSUE TITLE
crash after install 

### ISSUE THREAD

**Issue by nkeskes** [BlueBrain/Livre#379]
after make install livre crashes

.......
 PID.Thread  | Filename:line                    |   ms | Message
24790.Main     s/Livre/Equalizer/eq/init.cpp:106      21 Equalizer v2.0.0 initializing
24790.Main     /Pression/pression/plugin.cpp:166      21 Loaded 22 plugins from libPression.so.2.0.0
24790.Main     /Pression/pression/plugin.cpp:91       24 Initializing compression DSO /data/sismage/d820_1/users/keskes/Livre-ubuntu/lib/libPression.so.2.0.0 failed, 0 compression engines reported
24790.Main     vre/Lunchbox/lunchbox/dso.cpp:93       24 Can't open library /data/sismage/d820_1/users/keskes/Livre-ubuntu/lib/Debug/libPression.so.2.0.0: /data/sismage/d820_1/users/keskes/Livre-ubuntu/lib/Debug/libPression.so.2.0.0: cannot open shared object file: No such file or directory
24790.Main     /Pression/pression/plugin.cpp:166      32 Loaded 30 plugins from libEqualizer.so.2.0.0
Erreur de segmentation (core dumped)

and   libPression.so.2.0.0  remains referenced to  build directory and not to /usr/local/lib 

Any Idea ???

Regards
Noomane Keskes

**Comment by ErwannH** [comment]
Additionnaly:

- Equalizer is also not working after installing Livre
- Bug report also sent to Equalizer "NoThing working after make install (Ubuntu) #618"

Tried to import Livre in external Cmake. Need to add find_dependency(Lexis) in LivreConfig.cmake

Could be helpfull to fix that ;-)

Regards

**Comment by eile** [comment]
Related issue Eyescale/Equalizer#618

**Comment by eile** [comment]
I'm seeing the same thing, looking into fix.

**Comment by eile** [comment]
Should work with #381, if not reopen bug.
