### ISSUE TITLE
Clarify cache parameters

### ISSUE THREAD

**Issue by eile** [BlueBrain/Livre#73]
Documentation says today:
{code}
  --data-cache-mem arg (=1024)          Maximum data cache memory (MB) - caches
                                        the raw data read from I/O in system
                                        memory
  --texture-cache-mem arg (=3072)       Maximum texture cache memory (MB) -
                                        caches the texture data on GPU memory
  --texturedata-cache-mem arg (=8192)   Maximum texture data cache memory (MB) -
                                        caches the data that has been converted
                                        into internal texture format in system
                                        memory
{code}

--texture-cache-mem sounds ok (GPU cache). If I understand correctly, --texturedata-cache-mem is the CPU cache. But what is --data-cache-mem then, and why is it needed? And I guess the rendered set is just selected from the texture cache based on view point and SSE?

All options can drop '-mem', imo

**Comment by bilgili** [comment]
As I have said before;

Data on disk can be 16 bits and visualisation can be 8 bit therefore data needs to be normalised and it can be time consuming. So texture data is the normalised/converted data.

Data on the other hand the raw data read from the IO. It decreases the IO access in this sense.

The latter question answer is yes.

**Comment by bilgili** [comment]
We can maybe remove one of them. It is a bit too explicit I agree.

**Comment by tribal-tec** [comment]
+1
The two data caches can/should be merged from a user point of view. Then, the default size for this cache should have a reasonable default, some percentage of the system memory (today, the 1GB for data cache is typically too small).
