### ISSUE TITLE
Voxels not rendered

### ISSUE THREAD

**Issue by eile** [BlueBrain/Livre#96]
While debugging the 'events per voxel' functor, I create volumes which have 157 in a few voxels and none in the rest. In Livre, I cannot see the voxels. I used the Gauss transfer function which should show values in the middle of the spectrum, moving the maxima around. All I can get is a homogenous blob. Also used --samples-per-ray=4096 just in case the volume was undersampled.

**Comment by bilgili** [comment]
What is the sparsity of the volume. If 5 voxels in 1000000 voxel cube, I would say that a ray hitting a voxel is very low. You increased the sampling along the ray but we should need a ray density as well then, meaning sending more rays per pixel.

**Comment by eile** [comment]
164 events/voxels in the standard livre resolution (~256^3?)

**Comment by bilgili** [comment]
Really sparse. 164/16777216 probability there is a voxel. And there is perspective projection, where sparsity increases with the depth. In fact with sparsity, the problem should be reversed to project a volume to screen. Or, there is a Computer Graphics Forum paper :) We can try.

**Comment by eile** [comment]
Devils advocate: If I load it in Paraview, I see all 'on' voxels.

**Comment by bilgili** [comment]
Can you give me exact command line parameters ?

**Comment by bilgili** [comment]
It will be great if you give all command line parameters you are using.

**Comment by eile** [comment]
You'll need the new densityFunctor, which is not ready yet. Command line is:
```
bin/livre.app/Contents/MacOS/livre --volume fivoxSpikes://
```
Preliminary CR is at https://bbpcode.epfl.ch/code/15156

**Comment by bilgili** [comment]
They are rendered. Voxel values are 255 and the tf should be accordingly. You can create a tf file and load it.

**Comment by bilgili** [comment]
I have debugged a bit more. The issues are:
1) Due to number of rays that are casted from eye is not enough to sample when there is 1 voxel data. 
2) While sampling a voxel, I am using a GL_LINEAR sample from text3d, as a result the values are decreasing when sample is far from the center of the voxel. If I use GL_NEAREST, I can see them

Those are causing undersampling and biased voxels. Those can be resolved by using multiple samples along the ray. But where from is the question. You can sample from the surrounding voxels, but when voxels are big it will be a bit blurry.
Checking for the results.

**Comment by eile** [comment]
1) should not be an issue if one voxel is bigger than 1 pixel in screen space, which with the given SSE of 4 or 8 should always be the case.

**Comment by bilgili** [comment]
It is nothing to with the sse, this is all related to the texture sampling. Even with sse=1, ray may not be close to the voxel center.

**Comment by eile** [comment]
Yes, but if the voxel is bigger than a pixel, it should always be hit by at least one ray.

**Comment by bilgili** [comment]
With GL_NEAREST yes, with GL_LINEAR it will be different

**Comment by eile** [comment]
Yes == you can miss?

If so, please explain. Afaik, if the voxel is bigger than a pixel in screen space, nearest is guaranteed to hit the voxel since there must be at least one fragment where the nearest voxel to a given sampler position is filled. For example, if you rasterize a screen-aligned quad bigger than a pixel, at least one fragment is generated. Skype?

**Comment by bilgili** [comment]
Please check GL_LINEAR documentation. You wont miss but your value will be different than the center of the voxel. Therefore instead of 255 you will read 67. And if that is not in the tf, good luck rendering a voxel.

**Comment by eile** [comment]
I'm talking about NEAREST.

**Comment by eile** [comment]
With nearest, and a voxel bigger than a pixel, you should always get at least one "hit" to my understanding.

**Comment by bilgili** [comment]
Yes you are right with NEAREST and you have a rendering with it already when you set the Tex3D to use it. Currently it is GL_LINEAR as I have said before. And, as I also have said before also, GL_NEAREST causes blocky renderings. To have non-block results wit GL_NEAREST and to have GL_LINEAR like results you should have more samples per pixel or per ray.

**Comment by eile** [comment]
Ok, got it.

With linear, >1px voxels and a "ramp" transfer function we should then still see something, right? I could not get this to work either.

**Comment by bilgili** [comment]
Currently it works if you set all values to 1 1 1 1 except 0. This is not a "good solution", in fact far from it. I have to check how other people doing it right or if they are failing as well, I will have to improve sampling schemas.

**Comment by eile** [comment]
Sorry, I still don't understand: My transferFunction is Color = f( intensity ), with f( intensity ) { return Vector4( intensity, intensity, intensity, intensity ); }. The Shader should get a value > 0, therefore show me a more-or-less grey voxel. I cannot see this today - why?

**Comment by bilgili** [comment]
have you tried what I proposed ?

**Comment by eile** [comment]
We are talking around each other - let's discuss on Monday.

**Comment by bilgili** [comment]
Fixed with #145.
